using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

//https://www.youtube.com/watch?v=dO5BzWYqEdY&ab_channel=CodinginFlow

public class LevelController : MonoBehaviour
{
    [SerializeField] string nextScene;
 
    private void OnTriggerEnter2D(Collider2D collision)
    {
        if (collision.gameObject.name == "Player")
        {
            FindObjectOfType<SoundEffects>().PlayLevelComplete();
            CompleteLevel(); 
        }
    }

    private void CompleteLevel()
    {
        SceneManager.LoadScene(nextScene);
    }
}
